# Generated by Django 6.0.1 on 2026-01-22 19:55

import birdlib.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat_name', models.CharField(blank=True, max_length=50, null=True)),
                ('squad', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(blank=True, max_length=50, null=True)),
                ('genus', models.CharField(blank=True, max_length=50, null=True)),
                ('habitat', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='songs/')),
                ('logo_men', models.ImageField(blank=True, null=True, upload_to=birdlib.models.bird_file_directory_path)),
                ('logo_woman', models.ImageField(blank=True, null=True, upload_to=birdlib.models.bird_file_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
