# Generated by Django 6.0.1 on 2026-01-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdlib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='protection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='habitat',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
