# Generated by Django 6.0.1 on 2026-04-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdlib', '0003_bird_favourites'),
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observations',
            name='bird',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='birdlib.bird'),
        ),
    ]
