# Generated by Django 6.0.1 on 2026-04-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_observations_bird'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observations',
            name='date',
        ),
    ]
