# Generated by Django 6.0.1 on 2026-04-27 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_remove_observations_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='observations',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
