# Generated by Django 6.0.1 on 2026-04-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdlib', '0003_bird_favourites'),
        ('observations', '0004_observations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='bird',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdlib.bird'),
        ),
    ]
