# Generated by Django 6.0.1 on 2026-01-20 21:07

import userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=userprofile.models.product_preview_directory_path),
        ),
    ]
