# Generated by Django 6.0.1 on 2026-01-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/discussions/'),
        ),
    ]
