# Generated by Django 6.0.1 on 2026-01-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_alter_discussions_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussions',
            old_name='author',
            new_name='user',
        ),
    ]
