# Generated by Django 6.0.1 on 2026-02-04 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_rename_author_discussions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
