# Generated by Django 6.0.1 on 2026-02-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_discussions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussions',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
