# Generated by Django 6.0.1 on 2026-02-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_alter_discussions_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussions',
            name='date',
        ),
    ]
