# Generated by Django 6.0.1 on 2026-02-04 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_remove_discussions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussions',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
